### ISSUE TITLE
request: double side track

### ISSUE THREAD

**Issue by MoonshineSG** [dotscad/trains#1]
would it be possible to modify the lib to add wheel rails on both sides, above and under,  of the tracks ?

**Comment by ex-nerd** [comment]
I don't have any current plans to add any pre-made shapes for track with wheel wells on top/bottom but there's nothing stopping someone from using tracklib to do so.  Just have to rotate things and apply `difference()` where appropriate.  Some of the points ("splitters/junctions") might end up having too large of bridge prints, though, so I'd recommend only using it for the single-track parts.

That said, I wouldn't be averse to a patch.

**Comment by MoonshineSG** [comment]
so far I managed to modify "wood_rails_2d" to add the bottom rail, but adding the bevel is a bit tricky...

**Comment by himynameisulpa** [comment]
@MoonshineSG did you pull request it? Becaus I think it should be in the official repo too.

**Comment by MoonshineSG** [comment]
because it's been 4 years and since then my son stoped playing with trains and I kinda forgot about it :D....
feel free to close it...  or wait.. i'll do it..

**Comment by himynameisulpa** [comment]
But why is it not in this repository? Why didn't you make a pull request?
